openapi: '3.1.0'
info:
  title: GreetingService
  version: 1.0.0
servers:
  - url: http://localhost:8080/api
    description: Example service deployment.
paths:
  /emoji:
    get:
      operationId: getEmoji
      responses:
        '200':
          description: A success response with an emoji.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Emoji'
components:
    schemas:
        Emoji:
            type: string
